In [1]:
import torch
torch.__version__


'2.3.0'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.dim()
scalar.item()

7

In [5]:
vector = torch.tensor([7, 8])
print(vector)

tensor([7, 8])


In [6]:
vector.ndim

1

In [7]:
vector[1]

tensor(8)

In [8]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.9250, 0.4908, 0.0618, 0.8650],
         [0.6541, 0.8191, 0.9801, 0.8817],
         [0.6745, 0.8727, 0.8901, 0.9440]]),
 torch.float32)

In [9]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

In [10]:
torch.manual_seed(32)
linear = torch.nn.Linear(in_features = 2, out_features= 4)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 0.0102,  0.4397,  0.3114, -1.1090],
        [ 0.4280,  1.0047, -0.5589, -2.0396],
        [ 0.8458,  1.5698, -1.4292, -2.9702]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 4])


In [11]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
x.type(torch.float32).mean()

tensor(45.)

In [13]:
# Check for GPU
torch.cuda.is_available()

False

In [16]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [17]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [18]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)